name: Run tests

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'
  pull_request:
    branches:
    - master

jobs:
  test-github-cpuonly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.5']
        julia-arch: [x64]
        os: [ubuntu-latest]

    steps:
      - name: Set my secrets
        uses: webfactory/ssh-agent@v0.4.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout DSPopt.jl
        uses: actions/checkout@v2
      - name: Checkout libDsp
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan xgitlab.cels.anl.gov >> ~/.ssh/known_hosts
          git clone git@xgitlab.cels.anl.gov:kimk/libdsp.git libDsp
      - name: Set path to libDsp
        run: |
          cd libDsp && tar -zxvf DSP.tar.gz && cd ..
          echo "LD_LIBRARY_PATH=$PWD/libDsp:$PWD/libDsp/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - run: julia -e '@show ENV["LD_LIBRARY_PATH"]'
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
          
