name: Run tests

on:
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    branches:
      - master

jobs:
  test-github-cpuonly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.5']
        julia-arch: [x64]
        os: [ubuntu-latest]

    steps:
      - name: Set my secrets
        uses: appleboy/ssh-action@master
        with:
          hoat: "homes.cels.anl.gov"
          username: "kimk"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: "logins.cels.anl.gov"
          proxy_username: "kimk"
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            ls -al
            ls ddo
            cat ddo/hello.txt
