name: Run tests

on: [push, pull_request]

jobs:
  test-github-cpuonly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.5']
        julia-arch: [x64]
        os: [ubuntu-latest]

    steps:
      # - name: Checkout libDsp.so
      - uses: webfactory/ssh-agent@v0.4.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          repository: kibaekkim/libDsp
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          lfs: true

      # - uses: actions/checkout@v2
      # - uses: julia-actions/setup-julia@latest
      #   with:
      #     version: ${{ matrix.julia-version }}
      # - uses: julia-actions/julia-buildpkg@latest
      # - uses: julia-actions/julia-runtest@latest
      # - uses: julia-actions/julia-processcoverage@v1
      # - uses: codecov/codecov-action@v1
      #   with:
      #     file: lcov.info
          