name: Run tests

on:
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    branches:
      - master

jobs:
  test-github-cpuonly:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.5']
        julia-arch: [x64]
        os: [ubuntu-latest]

    steps:
      - name: Set my secrets
        uses: webfactory/ssh-agent@v0.4.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout libDsp
        run: |
          scp kimk@logins.cels.anl.gov:/nfs/gce/projects/ddo/hello.txt .
          ls
          cat hello.txt
